application: uploadersample # Application Identifierいれる
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# /get以下のページを見るには権限が必要にしたいならこんなふうに
#- url : /get
#  script: main.app
#  login: admin

# 静的ファイルはこんなふうにしてuploader以下にフォルダ作って入れる
#- url : /css
#  static_dir: css

- url: /.*
  script: main.app